openapi: "3.0.3"
info:
  title: Proza server
  version: "0.0.1"
servers:
  - url: '{protocol}://{host}/server'
    variables:
      host:
        default: 'localhost:4000'
      protocol:
        enum:
          - 'http'
          - 'https'
        default: 'http'
paths:
  /metadata:
    get:
      responses:
        200:
          description: Returns server metadata
          content:
            application/json:
              schema:
                $ref: '#components/schemas/ServerMetadata'
components:
  schemas:
    ServerMetadata:
      type: object
      properties:
        apiVersion:
          type: string
          description: semVer of api
          example: '1.0.0'
        enabledUserAuthMethods:
          type: array
          items:
            type: string
            enum:
              - github
              - oidc
              - google
              - linkedin
              - test
