name: Build and deploy

on:
  push:
    tags:
      - '[0-9].[0-9]+.[0-9]+'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set release version env
        run: |
          export TAG=${GITHUB_REF#refs/*/}
          echo "RELEASE_VERSION=$TAG" >> $GITHUB_ENV
          echo "RELEASE_VERSION_MINOR=$(echo "$TAG" | cut -d"." -f2)" >> $GITHUB_ENV
          echo "RELEASE_VERSION_MAJOR=$(echo "$TAG" | cut -d"." -f1)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/proza-api:${{ env.RELEASE_VERSION_MAJOR }}
            ${{ secrets.DOCKERHUB_USERNAME }}/proza-api:${{ env.RELEASE_VERSION_MINOR }}
            ${{ secrets.DOCKERHUB_USERNAME }}/proza-api:${{ env.RELEASE_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/proza-api:latest